# Generated by Django 3.2.6 on 2025-12-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20251207_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
